[package]
name = "bit-vm"
version = "0.1.0"
edition = "2021"

[lib]
name = "bitlib"
path = "src/bitlib.rs"

[[bin]]
name = "bit"
path = "src/main.rs"

[dependencies]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
